import React from 'react'

import { Helmet } from 'react-helmet'

import './screen3.css'

const Screen3 = (props) => {
  return (
    <div className="screen3-container">
      <Helmet>
        <title>exported project</title>
      </Helmet>
      <div className="screen3-screen3">
        <span className="screen3-text">
          <span>Learn . Network . Grow</span>
        </span>
        <span className="screen3-text02">
          <span>
            <span>Learn tech skills on the go with</span>
            <br></br>
            <span>Zoomer Technologies.</span>
          </span>
        </span>
        <img
          alt="Rectangle784752"
          src="/playground_assets/rectangle784752-qzt3-200h.png"
          className="screen3-rectangle78"
        />
        <span className="screen3-text07">
          <span>Get Started</span>
        </span>
        <img
          alt="Rectangle734752"
          src="/playground_assets/rectangle734752-6n84-200h.png"
          className="screen3-rectangle73"
        />
        <img
          alt="Rectangle744752"
          src="/playground_assets/rectangle744752-zc-200h.png"
          className="screen3-rectangle74"
        />
        <img
          alt="Rectangle754752"
          src="/playground_assets/rectangle754752-ay4x-200h.png"
          className="screen3-rectangle75"
        />
        <div className="screen3-pic3">
          <img
            alt="Vector4730"
            src="/playground_assets/vector4730-m2h.svg"
            className="screen3-vector"
          />
          <img
            alt="Vector4730"
            src="/playground_assets/vector4730-3xb.svg"
            className="screen3-vector01"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-3fmi.svg"
            className="screen3-vector02"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-vigp.svg"
            className="screen3-vector03"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-6ato.svg"
            className="screen3-vector04"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-evix.svg"
            className="screen3-vector05"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-a47ge.svg"
            className="screen3-vector06"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-lbgh.svg"
            className="screen3-vector07"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-vrdg.svg"
            className="screen3-vector08"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-2o4j.svg"
            className="screen3-vector09"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-uq2.svg"
            className="screen3-vector10"
          />
          <img
            alt="Vector4731"
            src="/playground_assets/vector4731-f0sg.svg"
            className="screen3-vector11"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-5ut.svg"
            className="screen3-vector12"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-h9wp.svg"
            className="screen3-vector13"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-mxe.svg"
            className="screen3-vector14"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-r9e.svg"
            className="screen3-vector15"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-cdxv.svg"
            className="screen3-vector16"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-a0t9.svg"
            className="screen3-vector17"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-l3ji.svg"
            className="screen3-vector18"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-o3oj.svg"
            className="screen3-vector19"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-ee9g.svg"
            className="screen3-vector20"
          />
          <img
            alt="Vector4732"
            src="/playground_assets/vector4732-gel9.svg"
            className="screen3-vector21"
          />
          <img
            alt="Vector4733"
            src="/playground_assets/vector4733-iqq6.svg"
            className="screen3-vector22"
          />
          <img
            alt="Vector4733"
            src="/playground_assets/vector4733-tk5.svg"
            className="screen3-vector23"
          />
          <img
            alt="Vector4733"
            src="/playground_assets/vector4733-u5iu.svg"
            className="screen3-vector24"
          />
          <img
            alt="Vector4733"
            src="/playground_assets/vector4733-txtg.svg"
            className="screen3-vector25"
          />
          <img
            alt="Vector4733"
            src="/playground_assets/vector4733-7hwi.svg"
            className="screen3-vector26"
          />
          <img
            alt="Vector4733"
            src="/playground_assets/vector4733-2uvl.svg"
            className="screen3-vector27"
          />
          <img
            alt="Vector4733"
            src="/playground_assets/vector4733-oby.svg"
            className="screen3-vector28"
          />
          <img
            alt="Vector4733"
            src="/playground_assets/vector4733-ogzj.svg"
            className="screen3-vector29"
          />
          <img
            alt="Vector4733"
            src="/playground_assets/vector4733-b16x.svg"
            className="screen3-vector30"
          />
          <img
            alt="Vector4734"
            src="/playground_assets/vector4734-0ko.svg"
            className="screen3-vector31"
          />
          <img
            alt="Vector4734"
            src="/playground_assets/vector4734-fpl9.svg"
            className="screen3-vector32"
          />
          <img
            alt="Vector4734"
            src="/playground_assets/vector4734-scw7.svg"
            className="screen3-vector33"
          />
          <img
            alt="Vector4734"
            src="/playground_assets/vector4734-5849.svg"
            className="screen3-vector34"
          />
          <img
            alt="Vector4734"
            src="/playground_assets/vector4734-svj.svg"
            className="screen3-vector35"
          />
          <img
            alt="Vector4734"
            src="/playground_assets/vector4734-awzs.svg"
            className="screen3-vector36"
          />
          <img
            alt="Vector4734"
            src="/playground_assets/vector4734-01sf.svg"
            className="screen3-vector37"
          />
          <img
            alt="Vector4734"
            src="/playground_assets/vector4734-j1w7.svg"
            className="screen3-vector38"
          />
          <img
            alt="Vector4734"
            src="/playground_assets/vector4734-v0wr.svg"
            className="screen3-vector39"
          />
          <img
            alt="Vector4735"
            src="/playground_assets/vector4735-av4s.svg"
            className="screen3-vector40"
          />
          <img
            alt="Vector4735"
            src="/playground_assets/vector4735-j6oa.svg"
            className="screen3-vector41"
          />
          <img
            alt="Vector4735"
            src="/playground_assets/vector4735-abrt.svg"
            className="screen3-vector42"
          />
          <img
            alt="Vector4735"
            src="/playground_assets/vector4735-hajl.svg"
            className="screen3-vector43"
          />
          <img
            alt="Vector4735"
            src="/playground_assets/vector4735-hya.svg"
            className="screen3-vector44"
          />
          <img
            alt="Vector4735"
            src="/playground_assets/vector4735-cusl.svg"
            className="screen3-vector45"
          />
        </div>
        <div className="screen3-frame4829869arrownextrighticon2">
          <div className="screen3-layer2">
            <img
              alt="Vector6879"
              src="/playground_assets/vector6879-6iab.svg"
              className="screen3-vector46"
            />
          </div>
        </div>
        <img
          alt="HomeIndicator5353"
          src="/playground_assets/homeindicator5353-o50u-200h.png"
          className="screen3-home-indicator"
        />
        <div className="screen3-status-bari-phone13">
          <div className="screen3-left-side">
            <div className="screen3-frame-status-bartime">
              <span className="screen3-text09">
                <span>1:41</span>
              </span>
            </div>
          </div>
          <div className="screen3-right-side">
            <div className="screen3-battery">
              <img
                alt="OutlineI195"
                src="/playground_assets/outlinei195-i9hn.svg"
                className="screen3-outline"
              />
              <img
                alt="BatteryEndI195"
                src="/playground_assets/batteryendi195-5cbv.svg"
                className="screen3-battery-end"
              />
              <img
                alt="FillI195"
                src="/playground_assets/filli195-yq9w.svg"
                className="screen3-fill"
              />
            </div>
            <img
              alt="WifiI195"
              src="/playground_assets/wifii195-h7r.svg"
              className="screen3-wifi"
            />
            <img
              alt="IconMobileSignalI195"
              src="/playground_assets/iconmobilesignali195-mvcu.svg"
              className="screen3-icon-mobile-signal"
            />
          </div>
        </div>
      </div>
    </div>
  )
}

export default Screen3
