import React from 'react'

import { Helmet } from 'react-helmet'

import './screen2.css'

const Screen2 = (props) => {
  return (
    <div className="screen2-container">
      <Helmet>
        <title>exported project</title>
      </Helmet>
      <div className="screen2-screen2">
        <span className="screen2-text">
          <span>Learn . Network . Grow</span>
        </span>
        <span className="screen2-text02">
          <span>
            <span>Learn tech skills on the go with</span>
            <br></br>
            <span>Zoomer Technologies.</span>
          </span>
        </span>
        <img
          alt="Rectangle734741"
          src="/playground_assets/rectangle734741-0ab-200h.png"
          className="screen2-rectangle73"
        />
        <img
          alt="Rectangle744742"
          src="/playground_assets/rectangle744742-g96-200h.png"
          className="screen2-rectangle74"
        />
        <img
          alt="Rectangle754742"
          src="/playground_assets/rectangle754742-bh5j-200h.png"
          className="screen2-rectangle75"
        />
        <div className="screen2-pic2">
          <img
            alt="Vector4722"
            src="/playground_assets/vector4722-azgv.svg"
            className="screen2-vector"
          />
          <img
            alt="Vector4722"
            src="/playground_assets/vector4722-udei.svg"
            className="screen2-vector01"
          />
          <img
            alt="Vector4722"
            src="/playground_assets/vector4722-g8fw.svg"
            className="screen2-vector02"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-a2e.svg"
            className="screen2-vector03"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-gda.svg"
            className="screen2-vector04"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-kva9.svg"
            className="screen2-vector05"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-39lg.svg"
            className="screen2-vector06"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-iwdm.svg"
            className="screen2-vector07"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-qm8.svg"
            className="screen2-vector08"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-o5i8.svg"
            className="screen2-vector09"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-ev7j.svg"
            className="screen2-vector10"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-oxa.svg"
            className="screen2-vector11"
          />
          <img
            alt="Vector4723"
            src="/playground_assets/vector4723-plop.svg"
            className="screen2-vector12"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-sjii.svg"
            className="screen2-vector13"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-exib.svg"
            className="screen2-vector14"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-ru.svg"
            className="screen2-vector15"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-obai.svg"
            className="screen2-vector16"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-fq9x.svg"
            className="screen2-vector17"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-pbvr.svg"
            className="screen2-vector18"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-d5d.svg"
            className="screen2-vector19"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-bojg.svg"
            className="screen2-vector20"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-fspo.svg"
            className="screen2-vector21"
          />
          <img
            alt="Vector4724"
            src="/playground_assets/vector4724-xsiu.svg"
            className="screen2-vector22"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-ur2.svg"
            className="screen2-vector23"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-6u8j.svg"
            className="screen2-vector24"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-t6x.svg"
            className="screen2-vector25"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-yoy.svg"
            className="screen2-vector26"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-0kmo.svg"
            className="screen2-vector27"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-mpu8.svg"
            className="screen2-vector28"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-rrt.svg"
            className="screen2-vector29"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-53le.svg"
            className="screen2-vector30"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-6a4.svg"
            className="screen2-vector31"
          />
          <img
            alt="Vector4725"
            src="/playground_assets/vector4725-fjt.svg"
            className="screen2-vector32"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-kyah.svg"
            className="screen2-vector33"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-5pk2.svg"
            className="screen2-vector34"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-epliq.svg"
            className="screen2-vector35"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-b0np.svg"
            className="screen2-vector36"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-uwj5.svg"
            className="screen2-vector37"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-r6sf.svg"
            className="screen2-vector38"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-iyo.svg"
            className="screen2-vector39"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-spyi.svg"
            className="screen2-vector40"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-lu9f.svg"
            className="screen2-vector41"
          />
          <img
            alt="Vector4726"
            src="/playground_assets/vector4726-atl.svg"
            className="screen2-vector42"
          />
          <img
            alt="Vector4727"
            src="/playground_assets/vector4727-5h7p.svg"
            className="screen2-vector43"
          />
          <img
            alt="Vector4727"
            src="/playground_assets/vector4727-zpxa.svg"
            className="screen2-vector44"
          />
          <img
            alt="Vector4727"
            src="/playground_assets/vector4727-eouw.svg"
            className="screen2-vector45"
          />
          <img
            alt="Vector4727"
            src="/playground_assets/vector4727-cup6.svg"
            className="screen2-vector46"
          />
          <img
            alt="Vector4727"
            src="/playground_assets/vector4727-6j1.svg"
            className="screen2-vector47"
          />
          <img
            alt="Vector4727"
            src="/playground_assets/vector4727-vda.svg"
            className="screen2-vector48"
          />
          <img
            alt="Vector4727"
            src="/playground_assets/vector4727-9cd.svg"
            className="screen2-vector49"
          />
          <img
            alt="Vector4727"
            src="/playground_assets/vector4727-5mbm.svg"
            className="screen2-vector50"
          />
          <img
            alt="Vector4727"
            src="/playground_assets/vector4727-0cis.svg"
            className="screen2-vector51"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-69i6.svg"
            className="screen2-vector52"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-wilv.svg"
            className="screen2-vector53"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-tu0p.svg"
            className="screen2-vector54"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-x5sv.svg"
            className="screen2-vector55"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-krzu.svg"
            className="screen2-vector56"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-8c6.svg"
            className="screen2-vector57"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-hqvj.svg"
            className="screen2-vector58"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-k46.svg"
            className="screen2-vector59"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-qycq.svg"
            className="screen2-vector60"
          />
          <img
            alt="Vector4728"
            src="/playground_assets/vector4728-lqsc.svg"
            className="screen2-vector61"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-iw9s.svg"
            className="screen2-vector62"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-x3kj.svg"
            className="screen2-vector63"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-2h1.svg"
            className="screen2-vector64"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-3zir.svg"
            className="screen2-vector65"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-8tk6.svg"
            className="screen2-vector66"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-6h8p.svg"
            className="screen2-vector67"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-hysb.svg"
            className="screen2-vector68"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-h5nt.svg"
            className="screen2-vector69"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-ba9.svg"
            className="screen2-vector70"
          />
          <img
            alt="Vector4729"
            src="/playground_assets/vector4729-al5s.svg"
            className="screen2-vector71"
          />
          <img
            alt="Vector4730"
            src="/playground_assets/vector4730-ygoe.svg"
            className="screen2-vector72"
          />
          <img
            alt="Vector4730"
            src="/playground_assets/vector4730-70f.svg"
            className="screen2-vector73"
          />
          <img
            alt="Vector4730"
            src="/playground_assets/vector4730-94kh.svg"
            className="screen2-vector74"
          />
          <img
            alt="Vector4730"
            src="/playground_assets/vector4730-ce86.svg"
            className="screen2-vector75"
          />
          <img
            alt="Vector4730"
            src="/playground_assets/vector4730-w0zq.svg"
            className="screen2-vector76"
          />
          <img
            alt="Vector4730"
            src="/playground_assets/vector4730-snn.svg"
            className="screen2-vector77"
          />
          <img
            alt="Vector4722"
            src="/playground_assets/vector4722-4fpq.svg"
            className="screen2-vector78"
          />
        </div>
        <img
          alt="HomeIndicator5352"
          src="/playground_assets/homeindicator5352-4qo-200h.png"
          className="screen2-home-indicator"
        />
        <img
          alt="Rectangle776887"
          src="/playground_assets/rectangle776887-f248-200h.png"
          className="screen2-rectangle77"
        />
        <img
          alt="Rectangle786887"
          src="/playground_assets/rectangle786887-ne5-200h.png"
          className="screen2-rectangle78"
        />
        <span className="screen2-text07">
          <span>Next</span>
        </span>
        <span className="screen2-text09">
          <span>Skip</span>
        </span>
        <div className="screen2-status-bari-phone13">
          <div className="screen2-left-side">
            <div className="screen2-frame-status-bartime">
              <span className="screen2-text11">
                <span>1:41</span>
              </span>
            </div>
          </div>
          <div className="screen2-right-side">
            <div className="screen2-battery">
              <img
                alt="OutlineI195"
                src="/playground_assets/outlinei195-l11.svg"
                className="screen2-outline"
              />
              <img
                alt="BatteryEndI195"
                src="/playground_assets/batteryendi195-sb1b.svg"
                className="screen2-battery-end"
              />
              <img
                alt="FillI195"
                src="/playground_assets/filli195-hx8k.svg"
                className="screen2-fill"
              />
            </div>
            <img
              alt="WifiI195"
              src="/playground_assets/wifii195-zhhw.svg"
              className="screen2-wifi"
            />
            <img
              alt="IconMobileSignalI195"
              src="/playground_assets/iconmobilesignali195-3c3.svg"
              className="screen2-icon-mobile-signal"
            />
          </div>
        </div>
      </div>
    </div>
  )
}

export default Screen2
